### ISSUE TITLE
hash salted is the same for all password

### ISSUE THREAD

**Issue by Mitch19** [panique/php-login-advanced#40]
Hello guys,

if i check my users through the DB, the initial part of the password is always the same

Isn't that a potential weakness?

thanks for the great work

M

**Comment by panique** [comment]
@Mitch19 You are obviosuly doing something very wrong as this is definitly not the case.

**Comment by Dominic28** [comment]
I guess he's talking about this part of the password hash: "$2y$10$" which is just the used algorithm^^

**Comment by panique** [comment]
@Mitch19 @Dominic28 Ah sorry I overread that (had a long night), Dominic is totally right here! That's intented and how this password hashing/salting works, have a look here for more info:
php.net/manual/en/function.password-hash.php

Cheers guys
