### ISSUE TITLE
im trying to find login form in documents

### ISSUE THREAD

**Issue by bhavesh1212310** [panique/php-login-advanced#42]
but I can't find them anywhere in it. can you tell me where the login form is located?

**Comment by areebmajeed** [comment]
The form is located in "Views" folder. Thanks.

**Comment by panique** [comment]
How the hell is it possible that people "don't find" this ? ???? Seriously... If you don'T get this,then you should not work in development or work with this script. I don't want to be mean, but it's 5seconds to find this, manually or via any search function in your IDE or via github... Dude...

**Comment by areebmajeed** [comment]
Chill, buddy.

**Comment by bhavesh1212310** [comment]
dude there's no login.php or something like that in my views folder I tried to find out manually by opening and searching in all documents buy I can't so I asked it here. by the way in which file LOG IN form is available? its not in register.php or in other folders

**Comment by bhavesh1212310** [comment]
hey thanks i got the code its in not_logged_in.php thanks and sorry  my mistake

**Comment by areebmajeed** [comment]
Peace.

**Comment by bhavesh1212310** [comment]
I'm facing another problem now... in not_loged_in.php page I added some CSS content to username and password and submit button but after this whenever I click the login button it just like refresh the page....but I think data is still stored of that season.... I added that is class="form-control" and placeholder. and to submit button I added class="btn btn-deafult " idk what's wrong I'm doing. I can send you complete source file if you want to see.

**Comment by panique** [comment]
Hey, this is a php script and your problem has absolutly nothing to do with the script. Maybe you should learn the basics first and read a book and follow some tutorials. Please respect that this here is a bug list and not a personal support forum for people who have absolutly no idea what they do.

**Comment by areebmajeed** [comment]
Hi.

Well, that sounds like Bootstrap. Have you even included Boostrap in CSS files? Please try contacting me at hello(at)areebmajeed(dot)me as I can help you get started with it. I've made scripts using this framework, and they all use Boostrap.
