### ISSUE TITLE
Database for MySQL + SQLite in advanced version

### ISSUE THREAD

**Issue by halojoy** [panique/php-login-advanced#51]
As you use PDO it is easy to let script support BOTH Mysql and SQLite.
I installed script at my website. And I wanted to use SQLite.
I made a try to edit in config and  Login class. But I ended up with "Database Connection" error.
THis is due to the different CREATE sql needed for SQLite.

If you could add support for SQLite also in this script it would be great.
It is not much work needed. Thanks to the PDO.

**Comment by panique** [comment]
Hey @halojoy , this would be a cool feature indeed, but the development on php-login-advanced has been stopped some time to ago to work on other projects. Sorry, but this means there will be no changes on the project anymore.

If you like, have a look on https://github.com/panique/huge, it's the "new" version of php-login-advanced.

**Comment by halojoy** [comment]
Thanks for quick reply.
