### ISSUE TITLE
Add reCaptcha to register form

### ISSUE THREAD

**Issue by Goldplate** [panique/php-login-advanced#52]
Hello, i want replace old captcha to reCaptcha, how to do that? Thank you

**Comment by panique** [comment]
I don't know, maybe you should do this by yourself ?

**Comment by austinkregel** [comment]
@Goldplate Please take a look at my fork of this amazing project for a working version of the new reCaptcha for registration.

**Comment by Goldplate** [comment]
@austinkregel wow thank you very much! :D

**Comment by panique** [comment]
@Goldplate  He, if you are searching for the link, have a look here :) https://github.com/panique/php-login-advanced/issues/45

**Comment by austinkregel** [comment]
@panique Thanks, I forgot about adding the link. 

@Goldplate if you need any help installing please ask in my issues section or email me, my email is on my github page. I've helped quite a few people install the script on their pages. I also just updated my master branch to allow for custom configurations.

**Comment by Goldplate** [comment]
@austinkregel thank you so much! :)
