### ISSUE TITLE
Manually login

### ISSUE THREAD

**Issue by blsn** [panique/php-login-advanced#54]
I would like to use the script in ajax website that loads content without refresh.

I understand that login via post data, means simply logging in via the login form, after the user has submitted his login/password successfully.

Since I use a callback function, I cannot use the above procedure for logging in. I want to perform a manual PHP login by passing the login form parameters to a callback function, e.g. as follows:

```
$login->loginWithPostData($_POST['user_name'], $_POST['user_password'], $_POST['user_rememberme']);
```

How to manually login?

**Comment by areebmajeed** [comment]
Why don't you kinda send a POST ping to the login.php file, and it'll automatically trigger a login session. However, there are still many better ideas to perform logins in a better way.

**Comment by blsn** [comment]
Do I need to write a batch script, what is the ping command..?
Can you give me an example of sending a POST ping to the file.
Thanks,
