### ISSUE TITLE
views/register.php

### ISSUE THREAD

**Issue by websiteninja** [panique/php-login-advanced#56]
```<input id="user_last_name" type="text" pattern="[a-zA-Z\-]{2,24}" name="user_last_name" value="<?php echo (isset($_POST['user_last_name']) ? ($_POST['user_last_name'] : ''); ?>" required />```

There is no filtering on the output. (htmlspecialchars). I was successfully able to implement XSS due to this.

**Comment by austinkregel** [comment]
Thank you for pointing this out. I have made a patch for my respective fork of the repo, and I will make the appropriate patches for the other active branch as this one as well.

**Comment by panique** [comment]
Thanks, I'll fix this ...

**Comment by panique** [comment]
Thanks, it's merged! :)
