### ISSUE TITLE
Verification Mail not sucessfully sent! Error: SMTP Connect()failed 

### ISSUE THREAD

**Issue by prabhatmech** [panique/php-login-advanced#58]
Hello Guys , 
While registration I am getting this Error - 

Verification Mail not sucessfully sent! Error: SMTP Connect()failed 

I updeted config.php 
as 
 * define("EMAIL_USE_SMTP", true);
 * define("EMAIL_SMTP_HOST", "ssl://smtp.gmail.com");
 * define("EMAIL_SMTP_AUTH", true);
 * define("EMAIL_SMTP_USERNAME", "xxxxxxxxxx@gmail.com");
 * define("EMAIL_SMTP_PASSWORD", "xxxxxxxxxxxxxxxxxxxx");
 * define("EMAIL_SMTP_PORT", 465);
 * define("EMAIL_SMTP_ENCRYPTION", "ssl");
 *
 * It's really recommended to use SMTP!
 *
 */
define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "ssl://smtpout.asia.secureserver.net");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "noreply@epcskills.com");
define("EMAIL_SMTP_PASSWORD", "mypassword");
define("EMAIL_SMTP_PORT", 465);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

/**

Guys please find the solutions. 

Thanks

**Comment by mikeq** [comment]
Do you have OpenSSL installed on your server and is the extension enabled
in PHP?

**Comment by prabhatmech** [comment]
my website hosting provider is godaddy . 

following steps i have done for php-login-advanced ->
1. I created a webspace email in godaddy as "noreply@epcskills.com " 
2. then find these info from "Email setup center for above id"
as ---
    define("EMAIL_USE_SMTP", true); 

define("EMAIL_SMTP_HOST", "ssl://smtpout.asia.secureserver.net");

    define("EMAIL_SMTP_AUTH", true); define("EMAIL_SMTP_USERNAME", "

    noreply@epcskills.com"); define("EMAIL_SMTP_PASSWORD", "mypassword");   

/note -mypassword is not my original password ./

   define("EMAIL_SMTP_PORT", 465); define("EMAIL_SMTP_ENCRYPTION", "ssl");


3. i uploaded all extracted zip form php-login-advanced in my website. 

when i register for new account then i am getting this error -

Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created.
Username (only letters and numbers, 2 to 64 characters)


please to solve this problem . 

Thanks

**Comment by panique** [comment]
How about reading the tutorial and doing exactly what it says ? Using godaddy and gmail is definitly not what the install tutorial recommends.

**Comment by prabhatmech** [comment]
i think they have not mentioned anywhere about godaddy

**Comment by panique** [comment]
Yes that's why you should not use "hosting" at godaddy! keep it professional and get a real server (or vagrant or anything like that).
