### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by jgqqb** [panique/php-login-advanced#61]
After clicking logout, I'm redirected back to login and it says, "You have been logged out."  If I go back to the previous page by clicking the back browser button and refresh, I'm logged in again.   In other words, the logout doesn't work properly.

**Comment by panique** [comment]
That's simply not true, and you can easily check this by looking into the code for one minute.

**Comment by jgqqb** [comment]
Look dumb ass I thought this was decent after looking at it.  I created a responsive site added this registration and login.  I thought I was ready to go.   Then tested it like above and was still logged in.   Then I downloaded the script again to see if I made a mistake somewhere.  

To my surprise and I'll be very nice about it ... it doesn't logout properly. Since I can go right back in to where I was previously.

**Comment by jgqqb** [comment]
Also one problem looking at the code and not testing it in a browser is a beginner mistake stupid ass.

**Comment by bckinit** [comment]
Wow you're right.  I was about to go live with my site and saw this post.  Damn it!!!!!  Chris you stupid fuck.

**Comment by hdididoit** [comment]
O MY GOSH... ARE YOU KIDDING????????  I used this code a year ago.  I AM NOT HAPPY.   No wonder people were getting their information stolen.   Looks like GITHUB isn't the place I thought it was.

**Comment by panique** [comment]
Are you retarded ? First, both of these 3 accounts belong to the same person. Nice try, troll. GitHub has a very competent anti-abuse team.

**Also:**
1. Testing your application is YOUR task, not mine or anybody in the open-source community.
2. This script has been installed and tested thousands of times, so there's a certain level of security inside, but also always a certain risk for bugs.
3. The issue you described doesn not exist in the live-demo.
4. If you want help, then post a least a bunch of useful information about your setup, your configs, etc. There can be 100s of reasons for this behaviour, if it really happens. Caching, cookie-domain, configs, ah what am I even helping you ?
5. Makes me sad to see lots of people workings 1000s of hours for free on a open-source project like this and then little idiots like you come up and blame open-source for your problems.
6. You'll get a notice from GitHub, and I think this was your first and also your very last day on this platform. Lifetime permaban.
7. Some of your sentences don't make any sense, no idea what you want to say.
8. I'll never understand how people like you get through life.

**Comment by jgqqb** [comment]
Seems quite funny how Panique uses the same speech for each issue.   

After testing the script again on your LIVE DEMO, not to my surprise, the demo has the same issue.  

I register, you should see my email in the db, and I logged in.  
After logging in, I logout.  
I click the browser back button and go back one page.
I refresh -  and I'm back in my account.   

Ya it works alright.  Again it doesn't work and your speeches are irrelevant.

**Comment by hdididoit** [comment]
I also tried and have the same problem.  I am sick and tired of crap developers that call their code top notch.  Then when issues arise they have no clue what the issues are.   You are right jgqqb how can someone who supposedly has this great knowledge have no clue about testing their work.

**Comment by panique** [comment]
I just checked that - in the live demo - and it's simply not true. Caching issue maybe.

And for the record: You have absolutly no right to come here, use "my" code for free and then rant here and say things like "stupid fuck" etc. This will have consequences for you.

If this would be real life, I would smash a bottle in your face for speaking like that to me.

**Comment by Murilirum** [comment]
That's the point of open source. YOU are given the opportunity to
contribute and help point out errors, one person can only do so much
testing before it completely takes away from the development time and
haults building anything at all.

No amount of people can be this stupid and unaware of the use of
open-source platforms and how to better use the software, this is a pretty
lousy attempt at defamation.

**Comment by bckinit** [comment]
If this is a caching issue you low life piece of shit then why is it happening on my computer.  Why is it happening on 5 browsers on my computer?   Also why is it happening on my phone you low life idiot?  You have a brain of piss ant.

**Comment by jgqqb** [comment]
Murilirum,   I agree but as you can read after my first post Panique the child get all huffy puffy over a bug.  People that want to post code should be aware that if there's a bug then someone may post it and ask for help or may say, "Hey this is what's happening".   Seems Panique can't take it.   

Then he says the live demo isn't that way.  I tried it and it is.  If fact tried it on a browser that I've never used testing his script.  I'm wondering how can that be cached if using a browser for the first time running his script?   

What it comes down to is Panique can't really code and doesn't have the knowledge to actually look into the issue.  Everything I've explained to him is simple there's no way he can win the argument.   

It's simple the code doesn't work.  I tried it locally, hosting server, his server and script .... and the same thing happens.  I used a browser that I haven't used running his script and the same thing happens.  Now what's the excuse that there's an issue?  

Let's see what he says now.

**Comment by panique** [comment]
This is a completely retarted discussion, you reported a bug, I checked it within minutes and posted that it cannot be reproduced in the live-demo. What's the deal ?
Then you came up with fake accounts and really bad rants like a little child, complaining. I even gave you some hints where the problem might be. Ah yes, and if you really want to report a bug or REALLY have a problem, then form a proper ticket, giving some useful information.

Very low level try of trolling. I'm not even sure if this is a real thing or if this is just a bored teenager trying to hate around on the internet on a saturday evening.

**Comment by Murilirum** [comment]
@jgqqb I'm with @panique on this one. You've gone way too far, if you can't
maturely use systems put in place to report a bug with a FREELY AVAILABLE,
PUBLIC download which you did not have to pay for, then you are in position
to make libellous claims towards the creator. You have provided no helpful
contributions to fixing it either by the way.

**Comment by jgqqb** [comment]
1. For one this isn't a fake a account Retard.  
2. Yes I reported a bug and you closed it a fucking fool.  
3.  I reproduced it in the demo THAT'S DEAL MORON.  
4.  Your hint was "it's cached".  And I said I tried many browsers and it's not CACHED.  

You need help stop boo fooing Obama and get a freaking job.

**Comment by jgqqb** [comment]
Murilirum I don't give a rats fucking ass.  I posted a nice, this is what's happening and dumbass closes it with no quesitons or anything useful.  If you want to post code you will be asked questions or someone may say, "I'm having issues".  If you Murilirum and/or Panique don't like to fucking bad.

**Comment by jgqqb** [comment]
Why would I post how to fix it??? I'm not a great developer that Panique who supposedly is.  Do you have any other excuses Murilirum?  What about Panique needs a psycho analysis?

**Comment by Murilirum** [comment]
I don't think he does, but you might.

**Comment by bckinit** [comment]
LOL you people are hilarious.  @jgqqb someone just told me murilirum and panique are butt buddies.  
That means you will never win this fight.  lol

**Comment by panique** [comment]
@jgqqb ????
No, I gave you several hints where the problem could be and you didn't even react on that.
I closed the ticket because the bug was not reproduceable and from the years of experieance dealing with ranting trolls in open-source projects - and your grammar - I think that in this case it's not a real bug. Closing a ticket is no offending to anybody, it's just moving the ticket from "todo" to "not super-important anymore". Everybody can always reopen a ticket.

FYI I take every little security risk VERY serious, and I spend A LOT of time unpaid to support anybody who needs help, but you're definitly not reporting a bug, just ranting. And, the project is not maintained for 1-2 years now.

I never said "I'm a great developer", what's wrong with you ? I'm not even working as a developer.

Regarding your weird Obama comment: I'm not a US citiizen, not living in the US (believe it or not, the world is bigger than just the USA!) and yes, I have a job that feeds some people.

Okay, this is really really weird and I'm unsure why I'm even reacting to this weirdness.

I'm definitly out now. You don't deserve it, but here's  potential fix: Check your setup! Check your configs! Reinstall the script from scratch in a clean environment and see if the problem still exists, so you can narrow down the problem.

**UPDATE:**
"butt buddies" ? Really ? Harrassing people by making anti-gay comments ? Really dude, in 2015 ? How old are you, 12 ?

**Comment by jgqqb** [comment]
@murilirum  did you write code to control how rubber dicks move in a guys ass?

**Comment by jgqqb** [comment]
Since you have short fuse and memory this is what I said,

"After clicking logout, I'm redirected back to login and it says, "You have been logged out." If I go back to the previous page by clicking the back browser button and refresh, I'm logged in again. In other words, the logout doesn't work properly. "

Hints where the problem could be?  I'm using where you have the code and under your domain AND the issue still exists.  The issue could of been it's cached, even though I've never tested it on your server so it wouldn't be cached.  So I try a different browser and it still happened.  I mean that's troubleshooting if I've ever seen troubleshooting AND you still go off!!!!   And you still don't understand troubleshooting.  I mean this has nothing to do with my setup.... why do you think I downloaded the script again before posting the issue??? I have better troubleshooting techniques than you will ever have.  

RANTING ... are you freaking serious????  Your the one who went off like a wild child.. you freak.

**Comment by bckinit** [comment]
Yes it's 2015, with you and murilirum who love boo fooing.  What?? You think that's normal panique?   Sticking your dick in some guys ass?   I understand you live in Germany and your a liberal nut fuck.  BUT to be serious anyone who would do such a thing has a mental illness.   I don't give a shit what the media says, Obama says, or even a liberal nut fuck in another country.   

If you're a man and you don't like pussy then you have a fucking problem no if and or buts.  

If when you see a woman and you don't want to fuck her < this is how men are made.  And you would rather butt fuck a man YOU HAVE A MENTAL PROBLEM AND SHOULD GET IT TAKEN CARE OF.  

Many people have so stop acting like it's normal.

**Comment by panique** [comment]
:)

This is gold! Excellent example showing that the most retarted, uneducated, narrow-minded people usually feel very very secure in their position, thinking everybody else around them is nuts.

And for the record: I support LGBT rights, but I'm not homosexual.

**Comment by bckinit** [comment]
:)  Yes it sure is gold.  A German nut sack ... we all know since WWII.   You have proven your inabilities in coding, testing, and the know how on how to react to problems.  <  It's obvious you're a  dumb ass.  You uneducated nut sack.  You probably married a feminist.  When she's around you hold your head down like a goof ball.  Then you come on here acting like a lunatic because you're unable to be a real man in your own home.  Very very said.  But normal in a liberal nut home.  

It's a free world you can support whatever you want to support but the facts are the facts. ....  If you're a man and you see a woman and you don't get those thoughts in your mind but rather think of gayness ... you have an issue ... it's very simple.     

Go watch and read the latest liberal droppings and convince yourself I'm not correct.

**Comment by panique** [comment]
Okay kid, it's time for bed for you now. If you don't want me to send a copy of your rant to your boss at work or to your parents, then leave GitHub now. Your parents would probably be very ashamed of you if they see what intelligent stuff you've done today on the internet.

And again, GitHub has a very powerful anti-abuse team. You are not anonymous on the web, never. Not behind a Tor proxy, and especially not when logging into one of the biggest tech sites on the planet.

Remember, the most retarted people always feel very very secure and safe, they simple don't know better. Attacking IT security people on the web is never a very clever move.

**Comment by bckinit** [comment]
What happened did your feminist wife smack you in the mouth again?  Now you come on here acting like I don't know the web wow.  Watch out everyone a big German pussy is acting like a bad ass AGAIN.  Believe me we have seen your bull before as your comments are for the weak.  I would love to see you and your other liberal nuts come after me.  LOL It would be a fucking delight... I'll show you what a real man is suppose to act and be like.

**Comment by panique** [comment]
Dude, you are 13! Keep it easy, learn proper english, finish school and learn something! Don't be the little loser you are right now. I'll block you now.

**Comment by Murilirum** [comment]
@panique Just make the report on the account then leave it alone. It's not worth any repercussive actions against your account. He's not contributing and just being a nuisance, if there's an option to block a user from a git, I'd recommend that option as well.

**Comment by panique** [comment]
@Murilirum Yeah I've blocked and reported that guy :) It was kind of interesting to discuss with such a guy, to be honest :)

Have a great night!

**Comment by Murilirum** [comment]
Yes, my Rubber(d)uck library is available next fall.

**Comment by Murilirum** [comment]
@panique Sounds good, I've used this login as a base for a few projects before I moved into Laravel which has it out of the box, but have not noticed this issue when tested. I haven't done any tests since this was mentioned but for the sake of all intents and purposes I'd at least recommend seeing if there is any sort of foundation to the claims made.
