### ISSUE TITLE
Code is working fine in the local development, but throws fatal error on the production live server

### ISSUE THREAD

**Issue by ummahusla** [panique/php-login-advanced#68]
`Fatal error: Call to undefined function password_verify() in /home/itbraing/public_html/production/classes/Login.php on line 277`

Any ideas what it might be? I've tested several times, I can easily login into my local server.

**Comment by areebmajeed** [comment]
Check your login.php file in the root, does it contain the following lines?

// Check for min. PHP version
if (version_compare(PHP_VERSION, '5.3.7', '<')) {
    exit('Sorry, this script does not run on a PHP version smaller than 5.3.7!');
} else if (version_compare(PHP_VERSION, '5.5.0', '<')) {
    // If you are using PHP 5.3 or PHP 5.4 you have to include the password_api_compatibility_library.php
    // (this library adds the PHP 5.5 password hashing functions to older versions of PHP)
    require_once('libraries/password_compatibility_library.php');
}

**Comment by ummahusla** [comment]
Thank you mate, that sorted this issue. Seems like I've deleted it by the accident. 

Have a nice day.

**Comment by panique** [comment]
By the way, using an older version than PHP 5.5 in production is not a good idea, 5.3 and 5.4 are really outdated and no security fixes are provided anymore.

**Comment by ummahusla** [comment]
@panique Thank you Chris for your suggestion. Yes I had 5.4 before, I didn't even realised that I forgot to update it. Changed it to 5.5.
