### ISSUE TITLE
Gravatar is not displaying image

### ISSUE THREAD

**Issue by ummahusla** [panique/php-login-advanced#69]
Is there any ideas why gravatar is not displaying the image?

I've got just a default grey image. 

This is the output what I get from `user_gravatar_image_url`
`http://www.gravatar.com/avatar/b60bd62fd797438e1f2947a82e28c1e8?s=50&amp;d=mm&amp;r=g&amp;f=y`

But when I use the refresh the page, I see still get [**grey avatar**](http://prntscr.com/ap0qn5)

**Comment by panique** [comment]
that's out of the framework, and this project is also dead for some years now

**Comment by ummahusla** [comment]
Yeah, I know that this project is not maintained anymore, just wanted to hear advice / guidance, for a possible issues

Thanks
