### ISSUE TITLE
Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created. 

### ISSUE THREAD

**Issue by kishanjvns** [panique/php-login-advanced#70]
Hello sir
I have fully configured this project on localhost and it works really fine for me.
But when I uploaded it on the server then I got an error something like this
Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created. 
Please tell me what should I do.
This is myonline address of the project
http://www.engineerspoint.net/Kishan/php-login-advanced-master/php-login-advanced-master/register.php

**Comment by panique** [comment]
read the readme like everybody else!

**Comment by kishanjvns** [comment]
I have read full readme.md file and I do follow each instructions that were mentioned , and I succesfully executed the project on localhost xampp, but I haven't enabled the ssl but it works fine in localhost.
I don't know what was I missing in it while I running this project on server accordingly to readme.md .
It shows me  
Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created. 
please help......:(

**Comment by panique** [comment]
this is not for xampp or so, install it properly please, and read into how to setup email correctly! if you are on windows (what you are as you use xampp) it's even so easy that you just have to download the linked email tool...

this "framework" is only dead for 3 years (?) now and it does not send email itself, it just uses the email tool installed on your system, but read the readme / install instructions, i dont want to explain it for the 100th time
