### ISSUE TITLE
Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created. please help......:(

### ISSUE THREAD

**Issue by kishanjvns** [panique/php-login-advanced#71]
I have read full readme.md file and I do follow each instructions that were mentioned , and I succesfully executed the project on localhost xampp, but I haven't enabled the ssl but it works fine in localhost.
I don't know what was I missing in it while I running this project on server accordingly to readme.md .
It shows me

Verification Mail NOT successfully sent! Error: SMTP Connect() failed.Sorry, we could not send you an verification mail. Your account has NOT been created.
please help......:(

**Comment by panique** [comment]
dude not again please! You've already posted the exact same question once and i've given you already a lot of help

**Comment by kishanjvns** [comment]
I know sir thanks you gave me your important time but that was not sufficient help really

**Comment by panique** [comment]
really ? read the readme and everything is fine, it's extremely easy

**Comment by areebmajeed** [comment]
It's clearly a problem related with your own configuration, not the script. Would you mind posting your SMTP configuration here (and censoring the sensitive details)?

**Comment by kishanjvns** [comment]
define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "kishanxxxxx@gmail.com");
define("EMAIL_SMTP_PASSWORD", "K8Pqsnaaserfv");
define("EMAIL_SMTP_PORT", 2525);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

**Comment by kishanjvns** [comment]
this smtp configuration is on server
define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "kishanjvns@gmail.com");
define("EMAIL_SMTP_PASSWORD", "K8PqsnHgd1JC");
define("EMAIL_SMTP_PORT", 2525);
define("EMAIL_SMTP_ENCRYPTION", "ssl");


and this is on localhost xampp


define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "kishanjvns@gmail.com");
define("EMAIL_SMTP_PASSWORD", "K8PqsnHgd1JC");
define("EMAIL_SMTP_PORT", 2525);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

both are same but this config is working on localhost xampp and when I uploaded it to server it geives me an error;

**Comment by kishanjvns** [comment]
this smtp configuration is on server
define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "kishanxxxx@gmail.com");
define("EMAIL_SMTP_PASSWORD", "K8Pqaaagd1JC");
define("EMAIL_SMTP_PORT", 2525);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

and this is on localhost xampp

define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "kishanxxxx@gmail.com");
define("EMAIL_SMTP_PASSWORD", "K8Pqaaagd1JC");
define("EMAIL_SMTP_PORT", 2525);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

both are same but this config is working on localhost xampp and when I uploaded it to server it geives me an error;

**Comment by areebmajeed** [comment]
Would be a brilliant idea if you could censor your password as I had mentioned in my previous reply. Anyway, replace the following the line:
define("EMAIL_SMTP_HOST", "mail.smtp2go.com");
With:
define("EMAIL_SMTP_HOST", "ssl://mail.smtp2go.com");

That should fix it.

**Comment by kishanjvns** [comment]
I change it as you recommend , but it gives me same error again.
and I m using godaddy server and I haven't configure ssl.
