### ISSUE TITLE
Text arrays

### ISSUE THREAD

**Issue by tonyjnrnwachi** [panique/php-login-advanced#72]
On the registration page how can I edit the text that is shown in the success message that says you should check your email for verification link?

		if (isset($registration)) {
			if ($registration->errors) {
				foreach ($registration->errors as $error) {
					echo $error;
				}
			}
			if ($registration->messages) {
				foreach ($registration->messages as $message) {
					echo $message;
				}
			}
		}
		?>

I think its this section but I am not sure where the text arrays are

**Comment by panique** [comment]
these texts are inside config/config.php :)

**Comment by tonyjnrnwachi** [comment]
That only fixes the text in the email I am trying to change the success message that shows on the page /register.php after you hit submit and everything is successful.

Apologies if I didn't make sense the first time round, fantastic script works perfectly with my project just been stuck for hours trying to change the text that outputs

"Your account has been created successfully and we have sent you an email. Please click the VERIFICATION LINK within that mail."

Maybe I don;t understand or need to define in the config file?

**Comment by panique** [comment]
ah okay it's in https://github.com/panique/php-login-advanced/blob/master/translations/en.php :)

**Comment by tonyjnrnwachi** [comment]
Your are the GREATEST thank you so much spent 3 hours and skipped that file over and over again

**Comment by panique** [comment]
:) no prob
